### ISSUE TITLE
Gnome error

### ISSUE THREAD

**Issue by marauderlabs** [cascadium/wsl-windows-toolbar-launcher#14]
Is gnome a pre-requisite? Can this be bypassed?
```
$ wsl-windows-toolbar
Usage: wsl-windows-toolbar [OPTIONS]
Try "wsl-windows-toolbar --help" for help.

Error: Invalid value for "--menu-file" / "-f": Could not open file: /etc/xdg/menus/gnome-applications.menu: No such file or directory
```

**Comment by marauderlabs** [comment]
Sorry. I missed that one bit in the pre-requisites. I guess that should solve it. Thanks!

**Comment by fquinner** [comment]
Oops yeah you could pick a different desktop (xfce would be lighter) or even write your own .menu file but that's how the tool figures out the directory structure for the launcher. Good luck!
