### ISSUE TITLE
 wsl-windows-toolbar failed to open

### ISSUE THREAD

**Issue by kroscek** [cascadium/wsl-windows-toolbar-launcher#15]
Using WSL 1, I tried to run it, but it returns an error:
(base) lemma@DESKTOP-FNQPG1F:~$ wsl-windows-toolbar
2020-07-19 18:46:28,090[WARNING]: Could not find imagemagick - some xpm icons may not convert correctly
Usage: wsl-windows-toolbar [OPTIONS]
Try "wsl-windows-toolbar --help" for help.

Error: Invalid value for "--menu-file" / "-f": Could not open file: /etc/xdg/menus/gnome-applications.menu: No such file or directory

**Comment by fquinner** [comment]
Hi there! Yeah you need a desktop package installed to run the script (its in the prerequisites section of README). It defaults to gnome but you can provide alternative `.menu` files with the -f argument if you prefer xfce4 etc. Its the menu file that generates the directory structure for the menu.

**Comment by kroscek** [comment]
Ah okay thanks mate!
