### ISSUE TITLE
Error when starting wsl-windows-toolbar -> TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by vampik33** [cascadium/wsl-windows-toolbar-launcher#24]
When I try to start wsl-windows-toolbar i have the following error:

Traceback (most recent call last):
  File "/home/vampik/.local/bin/wsl-windows-toolbar", line 7, in <module>
    from wsl_windows_toolbar.wsl_windows_toolbar import cli
  File "/home/vampik/.local/lib/python3.6/site-packages/wsl_windows_toolbar/wsl_windows_toolbar.py", line 26, in <module>
    uname().system,
TypeError: not enough arguments for format string

Also there is no folder:
%USERPROFILE%\.config\wsl-windows-toolbar-launcher\menus\WSL

**Comment by fquinner** [comment]
Whoops! Yeah looks like a bug I'll get that fixed soon. In the meantime be sure to run the script from *within* your WSL environment - that's what that error message was about to tell you until it failed.

**Comment by vampik33** [comment]
I run script _within_ WSL environment

**Comment by fquinner** [comment]
I pushed a change into the main branch there for the format error, but you shouldn't be hitting that issue unless maybe you're running a custom kernel? What does the output from this say:

    python3 -c "from platform import uname; print(uname())"

The code looks for "microsoft" in `uname().release` and "Linux" in `uname().system`.

**Comment by panaris** [comment]
I think you need to write Microsoft with capital M

**Comment by vampik33** [comment]
> I pushed a change into the main branch there for the format error, but you shouldn't be hitting that issue unless maybe you're running a custom kernel? What does the output from this say:
> 
> ```
> python3 -c "from platform import uname; print(uname())"
> ```
> 
> The code looks for "microsoft" in `uname().release` and "Linux" in `uname().system`.

uname_result(system='Linux', node='DESKTOP-VPV8E5L', release='4.4.0-18362-Microsoft', version='#1049-Microsoft Thu Aug 14 12:01:00 PST 2020', machine='x86_64', processor='x86_64')

**Comment by fquinner** [comment]
Wow yeah they have changed that its lowercase M on mine will but in a fix for that shortly

**Comment by fquinner** [comment]
Just pushed in a fix if you can check if has fixed the issue?

    pip install --upgrade git+https://github.com/cascadium/wsl-windows-toolbar-launcher.git

If that works I'll push it up to pypi, thanks for reporting!

**Comment by panaris** [comment]
No, didnt work
WSL Linux environment required (detected: Linux [4.4.0-18362-Microsoft])

**Comment by fquinner** [comment]
That's weird I hacked the versions here locally for testing to contain those strings reported and it worked ok. Are you definitely testing with 0.6.2 (because the formatting fix was pushed in yesterday, but that was still 0.6.1 - the case insensitive fix is in 0.6.2)?

**Comment by panaris** [comment]
That error is showing when I try to upgrade
pip install --upgrade git+https://github.com/cascadium/wsl-windows-toolbar-launcher.git

**Comment by fquinner** [comment]
Ahhhh it's in setup.py as well... hang on

**Comment by fquinner** [comment]
OK try again now please... 0.6.3

**Comment by panaris** [comment]
OK but I think that you should specify that you must not run wsl-windows-toolbar as su

**Comment by fquinner** [comment]
> OK but I think that you should specify that you must not run wsl-windows-toolbar as su

Good call just raised #25 for that one.

**Comment by fquinner** [comment]
Should be fixed now in 0.6.3
