### ISSUE TITLE
Unable to launch Intellij from WSL

### ISSUE THREAD

**Issue by rhys-saldanha** [cascadium/wsl-windows-toolbar-launcher#28]
This is slightly outside the scope of this tool, which seems to be working as intended, but you show yourself opening CLion running WSL on the README so I thought I'd ask anyways.

I've installed Intellij manually to `/opt` as described by [this section](https://www.jetbrains.com/help/idea/installation-guide.html#standalone). Running `wsl-windows-toolbar-launcher`, a shortcut to Intellij is not created. I made my own, to point to `idea.sh`, but it is not able to start.

How did you get CLion working so flawlessly?

**Comment by fquinner** [comment]
Great question! The toolbar works by emulating the bits and pieces that would normally put together a real desktop menu. This includes search paths for .desktop files which the /opt method probably won't do.

For the Jetbrains tools I always use the Jetbrains toolbox for installation (you can download from their site). It sets the installation to your home directory and sets up all the desktop files in the right place for the freedesktop menus to find them :).

**Comment by rhys-saldanha** [comment]
I have the toolbox installed in Windows, but I'm guessing I should instead install the toolbox in WSL?

**Comment by fquinner** [comment]
Yup so you install jetbrains toolbox inside wsl as your own user, then run it from within the wsl environment, install all the tools you use, then re-run the wsl toolbar launcher script to update your menu items!

**Comment by rhys-saldanha** [comment]
I'm going to leave some helpful links here in case anyone else finds this thread.

To install `jetbrains-toolbox` more easily: [nagygergo/jetbrains-toolbox-install](https://github.com/nagygergo/jetbrains-toolbox-install)
A helpful post that walks through installing an X Server on Windows and running the toolbox: [medium.com/@ragin](https://medium.com/@ragin/development-under-windows-under-linux-with-wsl2-intellij-860daf601b61)
