### ISSUE TITLE
rc_file is not respected and zsh support.

### ISSUE THREAD

**Issue by oleg-andreyev** [cascadium/wsl-windows-toolbar-launcher#32]
Command
```bash
 wsl-windows-toolbar -r ~/.zshrc
```

Result:
```bash
#!/bin/bash -i
source /home/olega/.bashrc
cd "/home/olega"
env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/phpstorm_phpstorm.desktop /snap/bin/phpstorm  > /dev/null 2>&1 &
disown
```

Expected

```bash
#!/bin/zsh -i
source /home/olega/.zshrc
```

**Comment by fquinner** [comment]
The rc_file option is more for a bashrc or bash compatible zshrc where you want to source additional stuff before launching using bash in the bash template that comes with the package.

To use an alternative shell, you'd need to specify a template.

To do this, create a file which is based on a modified version of this: https://raw.githubusercontent.com/cascadium/wsl-windows-toolbar-launcher/master/wsl-windows-toolbar-template.sh.j2

And pass it in with `-J /path/to/your/template.j2`.

**Comment by oleg-andreyev** [comment]
@fquinner thanks!
