### ISSUE TITLE
Custom j2-template seems not to be working

### ISSUE THREAD

**Issue by NorseJedi** [cascadium/wsl-windows-toolbar-launcher#35]
I'm trying to make this use zsh rather than bash, and found a closed issue (#32) where it was explained you have to make use of a custom template for that. So I made this template where I only changed the first line:

> #!/bin/zsh -i
> 
> source {{rcfile}}
> 
> {% if exec_dir is defined and exec_dir != "" %}
> 
> cd "{{exec_dir}}"
> 
> {% endif %}
> 
> {% if run_in_terminal is defined and run_in_terminal == True %}
> 
> {{command}}
> 
> {% else %}
> 
> {{command}} > /dev/null 2>&1 &
> disown
> 
> {% endif %}

I then run this command:
`wsl-windows-toolbar -r ~/.zshrc -J ~/etc/wslmenu-template.sh.j2`

The output of the command indicates that the file is being used:
> 2021-02-18 20:50:28,843[INFO]: jinja_template_shell = /home/roy/etc/wslmenu-template.sh.j2

There are no errors in the output, just a warning about it not finding an icon-file for windows, which I assume isn't relevant.

However, the shortcut scripts created in `%USERPROFILE%/.config/wsl-windows-toolbar-launcher/metadata/` do not reflect this, they're created with `#!/bin/bash -i` at the first line.

**Comment by fquinner** [comment]
Thanks yeah this looks like a bug. It will only work if values for both `-J` (shell template) *and* `-j` (batch template) are provided - will need to fix that. In the meantime try providing both and it should work.

**Comment by NorseJedi** [comment]
Thank you, yes, that works :)
