### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by slococo** [cascadium/wsl-windows-toolbar-launcher#36]
Hi! Im having a problem starting wsl-windows-toolbar.
It gives me this error: The powershell.exe application must be in the current user's executable $PATH.
Do you know what can i do?

**Comment by fquinner** [comment]
You need to have powershell.exe in your path, so most likely:

    export PATH=/mnt/c/Windows/System32:$PATH

Before running the script.

Usually its added when you launch wsl but depends on your `.bashrc`. Note you shouldn't run with sudo (just in case you're doing that).

**Comment by slococo** [comment]
Thanks!
