### ISSUE TITLE
raw_input error

### ISSUE THREAD

**Issue by bachittle** [cascadium/wsl-windows-toolbar-launcher#37]
this is what I get when running the wsl-windows-toolbar script:
![image](https://user-images.githubusercontent.com/39804642/118564809-fe770380-b73e-11eb-94c5-36887fc00bca.png)

**Comment by bachittle** [comment]
I found switching raw_input to confirm works: https://click.palletsprojects.com/en/8.0.x/prompts/#input-prompts

**Comment by jswetzen** [comment]
I found [this SO answer](https://stackoverflow.com/questions/954834/how-do-i-use-raw-input-in-python-3) and made a small change that made it work.
```
#from click._compat import raw_input
from six.moves import input as raw_input
```

**Comment by jswetzen** [comment]
Never mind, I was on the pip version so it's probably fixed in git.
