### ISSUE TITLE
[support] Not able to run Jetbrains Toolbox

### ISSUE THREAD

**Issue by serpro69** [cascadium/wsl-windows-toolbar-launcher#43]
Hi,

First wanted to thank you for this nice piece of software :) 

I know this isn't related to the tool itself, but I saw you running jetbrains products in your demo so maybe you could help me.
I'm trying to run jetbrains toolbox that is installed in WSL2 but it's not launching, while some other apps work fine.

Steps: 
1. I've installed the toolbox using this script: https://github.com/nagygergo/jetbrains-toolbox-install
2. Re-run wsl-windows-toolbar
3. Launch toolbox from the toolbar -> nothing happens
3.1 Alternatively launching toolbox from WSL cli doesn't do anything either

I am able to run other gui apps, like `xeyes` from WSL terminal, and I'm also able to run apps from the toolbar, like htop and vim.

I've tried adding:
```
dbus_status=$(service dbus status)
if [[ $dbus_status = *"is not running"* ]]; then
  sudo service dbus --full-restart
fi
```
at the beginning of my `~.zshrc` file, but that didn't help either.

And I tried to launch this from the cmd as well:
```
C:\Users\sergeip>wsl.exe -d Ubuntu-20.04 -u sergio -- source ~/.zshrc ; env; jetbrains-toolbox
HOSTTYPE=x86_64
LANG=C.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Users/sergeip/AppData/Local/Microsoft/WindowsApps
TERM=xterm-256color
WSLENV=
WSL_INTEROP=/run/WSL/31905_interop
NAME=rocinante
HOME=/home/sergio
USER=sergio
LOGNAME=sergio
SHELL=/usr/bin/zsh
WSL_DISTRO_NAME=Ubuntu-20.04
SHLVL=1
PWD=/mnt/c/Users/sergeip
OLDPWD=/mnt/c/Users/sergeip
_=/usr/bin/env
```
which does not give any errors.

Here's the .desktop file:
```
✓ ~→ less ~/.local/share/applications/jetbrains-toolbox.desktop

[Desktop Entry]
Icon=/home/sergio/.local/share/JetBrains/Toolbox/toolbox.svg
Exec=/home/sergio/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox %u
Version=1.0
Type=Application
Categories=Development
Name=JetBrains Toolbox
StartupWMClass=jetbrains-toolbox
Terminal=false
MimeType=x-scheme-handler/jetbrains;
X-GNOME-Autostart-enabled=true
StartupNotify=false
X-GNOME-Autostart-Delay=10
X-MATE-Autostart-Delay=10
X-KDE-autostart-after=panel
```

Launching the app from the toobar does actually create the process in WSL:
```
✓ ~→ ps aux | grep jetbrains

sergio   10013 27.0  0.0  12124  2356 ?        Rsl  11:29   0:00 /home/sergio/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox
sergio   10022  299  0.2 3475908 106672 ?      Rl   11:30   0:02 ./jetbrains-toolbox
```

Any ideas what else I could try here?

Thanks a lot for the help!

**Comment by serpro69** [comment]
Found this article: https://ragin.medium.com/development-under-windows-under-linux-with-wsl2-intellij-860daf601b61
which suggested installing additional packages with apt:
```
sudo apt install libcups2 libpangocairo-1.0-0 libatk-adaptor libxss1 libnss3 libxcb-keysyms1 x11-apps libgbm1
```

Doesn't seem to help in my case.

**Comment by fquinner** [comment]
I actually had a similar issue recently, I didn't have Java installed... somewhat irritating that it silently failed without a clue but that's what I found anyway hopefully its something simple like that for you!

**Comment by serpro69** [comment]
Hi @fquinner , thanks for the tip. Do you mean java in windows or WSL?
I don't have java in windows, I do have it in WSL though.

I've also tried to install appimage launcher, which installed also a bunch of other dependencies, and now I'm able to see the toolbox icon popping up in windows, but I still don't see the application window or anything. And the execution of jetbrains-toolbox now prints this:
```
✓ ~/Downloads/jetbrains-toolbox-1.21.9547→ ./jetbrains-toolbox
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-sergio'
Failed to connect to bus: No such file or directory
```
I did try to restart the `dbus` service, but that didn't change anything really.

I'll try to install java under windows as well and see if that helps.

**Comment by serpro69** [comment]
OK, so installing java under Windows fixed it. Thanks a lot for the tip @fquinner .

**Comment by serpro69** [comment]
Just in case someone else stumbles onto this, this is what helped me:
```
sudo apt install libcups2 libpangocairo-1.0-0 libatk-adaptor libxss1 libnss3 libxcb-keysyms1 x11-apps libgbm1 libxkbcommon-dev
sudo add-apt-repository ppa:appimagelauncher-team/stable
sudo apt update
sudo apt install appimagelauncher
```

Looks like appimagelauncher brings in some extra dependencies with it that are required to run the jetbrains toolbox.
If I run `sudo apt autoremove` and remove the dependencies that were pulled by appimagelauncher, then the toolbox stops working (it launches, but I only see a white window).
Would be nice to figure out which dependency is the culprit here, but there are quite a few of those.

**Comment by serpro69** [comment]
Another issue found with the jetbrains toolbox is that it does not close properly. If you see a black screen when launching the toolbox - close the X11 server on windows and re-launch it (possibly wsl might need a restart as well, run `wsl --shutdown` from cmd), then launch the toolbox again.
This is really annoying, but at least there are workarounds for these issues :D

**Comment by ShawnTalbert** [comment]
Wait, how is it possible that installing Java on Windows is required? Are we sure that's a dependency? Sounds like it breaks the very isolation I'm trying to achieve with WSL?

**Comment by fquinner** [comment]
> Wait, how is it possible that installing Java on Windows is required? Are we sure that's a dependency? Sounds like it breaks the very isolation I'm trying to achieve with WSL?

It's not there were crossed wires. You need Java installed inside WSL only. Installing in windows will have no effect.

**Comment by ShawnTalbert** [comment]
I never did get the toolbox to diplay on VcXsrv. It just left a little icon window but couldn't open  it :(.

**Comment by danielorbach** [comment]
For strugglers in the future, What did the trick for me was to install `xdg-mime`.
I saw that is was missing by looking at the latest log file under `~/.local/share/JetBrains/Toolbox/logs`.

_Note I am running Windows 11 build 21H2 (OS Build 22000.778)_

**Comment by linghengqian** [comment]
- I have to say I don't understand what's in `~/.local/share/JetBrains/Toolbox/logs` at all, it doesn't ask me to install any dependencies at all.
- The magic is when I execute `sudo apt install appimagelauncher` everything works fine. From this point of view AppImage is far inferior to Snapcraft and Flathub.🤷‍♂️

**Comment by linghengqian** [comment]
- I opened https://youtrack.jetbrains.com/issue/TBX-8589 to track this issue.

**Comment by jongracecox** [comment]
This thread was very helpful, but didn't end up solving my issue that was very similar. I tried all the steps , but what helped me in the end was disabling hardware acceleration using:

```bash
LIBGL_ALWAYS_SOFTWARE=1 jetbrains-toolbox
```

**Comment by freynder** [comment]
When running:
```.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox```
I get:
```
Failed to create Skia OpenGL context!
Cannot init graphic context
```
with the black screen.

Killing both processes and running:
```
LIBGL_ALWAYS_INDIRECT=0 .local/share/JetBrains/Toolbox/bin/jetbrains-toolbox
```
seems to work consistenly. No other GL env variables.
