### ISSUE TITLE
[Suggestion] Add a disclaimer about firewall debugging in the README.md

### ISSUE THREAD

**Issue by LouizFC** [cascadium/wsl-windows-toolbar-launcher#45]
Greetings.

I found out this repo while trying to configure a x11 server with wsl2. From my research, this repo is one of the main sources that people are currently pointing to when trying to help others.

That said, I had a problem discovering which port I needed to add in the firewall rule ,I created the rule for port 6000, but after enabling firewall logs, I discovered that the server was running in 6001.

I also had a problem with the `DISPLAY` variable, my x server was running on :1.0 instead of :0.0.

I think that a mini-guide of how to enable firewall logs and a disclaimer to check the x server connection url would be very helpful to people coming to this repository with this kind of problem, so before I open a PR, I wanted to know if this kind of information is in the scope of this repo.

**Comment by fquinner** [comment]
Just replaced:

TCP port 6000 (most likely)

With:

TCP port 6000 (most likely, but verify with display number / X11 server documentation before continuing)

I think that's all that realistically we can do here without documenting every X11 server which I would rather avoid. Thanks for pointing out.
