### ISSUE TITLE
Issue with Firewall Rules method & README suggestion 

### ISSUE THREAD

**Issue by rdmolony** [cascadium/wsl-windows-toolbar-launcher#5]
Thanks @fquinner for your X-server Firewall instructions.  They've been really helpful in setting up a local X-server for WSL2 - I found your Github from [here](https://github.com/microsoft/WSL/issues/4106)

1. I unfortunately couldn't get your __Firewall Rules__ method to work.  My workaround was to enable Public access for VcXsrv in Windows Defender Firewall -> Advanced Settings -> Inbound Rules.  Just disabling the Block rule also works. 

![image](https://user-images.githubusercontent.com/50016440/80622183-59f52700-8a40-11ea-834e-1d21f52b789b.png)

2. Would you please be able to add that TCP port 6000 represents VcXsrv and can be verified by entering `netstat -ab` in an elevated command prompt?

> "Now, right click on Inbound Rules and select New Rule..., select TCP port 6000 (most likely) and select defaults. This will open up your public network for this port... which is also not what you want. What you want is to only allow traffic from the WSL subnet. So refresh the list, scroll to your recently created name, right click and go to properties. Now under Scope, go to Remote IP address, Select These IP addresses and add in 172.16.0.0/12 to limit the subnets which can access this port to the WSL subnet. It should look something like"

I didn't know what TCP port 6000 referred to (and so wasn't 100% whether or not it would be the same on my computer) and found out thanks to this [howtogeek guide](https://www.howtogeek.com/howto/28609/how-can-i-tell-what-is-listening-on-a-tcpip-port-in-windows/).  Entering `netstat -ab` in an elevated command prompt shows all of the ports associated with each app.  By doing this I realised that port 6000 represents VcXsrv.

**Comment by fquinner** [comment]
Thanks @rdmolony I haven't forgotten about you though some of these points are X11 server specific though (I use X410 for example) and multiple ports are possible, but yeah will add a few extra specifics thanks for raising :).
